### PR TITLE
 Add referenceName to Pileup and fix warning

### LINKED ISSUE #335: make Pileup.referenceName work even when the pileup is empty
We currently load the reference name (i.e. the contig) from the first read in the pileup: https://github.com/hammerlab/guacamole/blob/master/src/main/scala/org/hammerlab/guacamole/pileup/Pileup.scala#L43

This makes an assertion error if the pileup is empty. We should carry around the reference name in the pileup so it works in this case.

As a separate issue, `referenceName` is kind of an awkward name for this. Maybe we should rename it to `contig` or `chromosome`?

### PR DESCRIPTION
**Pull request by timodonnell**
* Add referenceName to Pileup as an attribute. This makes it possible to access this field even when the Pileup is empty. Closes #335.
* Fix a compile warning  in `ReadSet`.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/guacamole/336)

### CODE REVIEW

File: src/main/scala/org/hammerlab/guacamole/ReadSet.scala [hunk 1]
```diff
@@ -53,8 +53,8 @@ case class ReadSet(
 
   lazy val mappedPairedReads: RDD[PairedRead[MappedRead]] = reads.flatMap(read =>
     read match {
-      case rp: PairedRead[MappedRead] => Some(rp)
-      case _                          => None
+      case rp if rp.isMapped => Some(rp.asInstanceOf[PairedRead[MappedRead]])
```
Comment (arahuja) [inline src/main/scala/org/hammerlab/guacamole/ReadSet.scala]: This doesn't check that `rp` is a `ReadPair` though, it may just be a `MappedRead`

Comment (timodonnell) [inline src/main/scala/org/hammerlab/guacamole/ReadSet.scala]: Good catch, fixed.
